name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: add repo
      run: sudo add-apt-repository ppa:bitcoin/bitcoin
    - name: update
      run: sudo apt-get update
    - name: dep install
      run:  sudo apt-get install -y libdb4.8-dev libdb4.8++-dev libevent-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev libboost-all-dev libssl-dev 1.0.2g    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
